
# File: k8s/postgres-secret.template.yml
# Purpose: A template for creating the PostgreSQL secret. DO NOT commit the filled-in file.

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  # IMPORTANT: Replace this with a strong, randomly generated password.
  POSTGRES_PASSWORD: "CHANGEME_REPLACE_WITH_REAL_PASSWORD"